services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack:3
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,iam,sts
      - AWS_DEFAULT_REGION=eu-west-1
      - PERSISTENCE=1
      - DEBUG=0
      - FORCE_NONINTERACTIVE=1
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - ./volume:/var/lib/localstack
      - ./init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s