---
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded

- name: Update AIDE database
  ansible.builtin.command: aide --update
  changed_when: true
  ignore_errors: true

- name: Initialize AIDE database
  ansible.builtin.command: aideinit -y
  changed_when: true
  ignore_errors: true

- name: Reconfigure unattended-upgrades
  ansible.builtin.command: dpkg-reconfigure -plow unattended-upgrades
  changed_when: false
  ignore_errors: true